databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: ailsr
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: build exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan : free
    maxmemoryPolicy: noeviction