databases:
  - name: budget_app
    databaseName: budget_app_wqwx
    user: budget_app_wqwx_user

services:
  - type: web
    name: budget_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetapp_wqwx
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false